from statuses.status_game import STATUS_GAME
from settings import WIDTH, HEIGHT, HALF_WIDTH

BUTTONS = [
    ((20, HEIGHT-110), (300, 90), 'NEXT_LEVEL', STATUS_GAME.GAME_PROCESS),
    ((HALF_WIDTH-200, HEIGHT-110), (300, 90), 'RESTART LEVEL', STATUS_GAME.GAME_PROCESS_RESTART),
    ((WIDTH-420, HEIGHT-110), (300, 90), 'Exit', STATUS_GAME.EXIT)
]
